# Anki-Assimil V3 Configuration

# Anki settings
anki:
  hebrew_deck: "Hebrew from Scratch"
  assimil_deck: "Assimil Hebrew"
  connect_url: "http://localhost:8765"
  
# File paths
paths:
  assimil_course_dir: ~/Dropbox/Hebrew/Assimil Hebrew
  anki_media_dir: ../v2/test-data/anki-media

# Processing settings  
processing:
  max_lessons: 20
  skip_files:
    - T00-TRANSLATE.mp3
  word_match_threshold: 5
  similarity_candidates: 2
